# Generated by Django 4.2.7 on 2023-11-29 19:59

from django.db import migrations, models
import functools
import vendor_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0002_remove_vendor_fulfillment_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Address'})]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.TextField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Contact Details'})]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Name'}), vendor_api.models.validate_alphanumeric]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=50, unique=True, validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Vendor Code'})]),
        ),
    ]
