# Generated by Django 4.2.7 on 2023-11-30 08:53

from django.db import migrations, models
import functools
import vendor_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0003_vendor_fulfillment_rate_alter_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Delivery Date'})]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Issue Date'})]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Items'})]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Order Date'})]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=20, unique=True, validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'PO Number'})]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'Quantity'})]),
        ),
    ]
