# Generated by Django 4.2.7 on 2023-11-30 11:24

from django.db import migrations, models
import functools
import vendor_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0006_alter_purchaseorder_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=20, unique=True, validators=[functools.partial(vendor_api.models.validate_not_empty, *(), **{'field_name': 'PO Number'})]),
        ),
    ]
